name: Test container and code execution

on: workflow_dispatch
jobs:
  testcontainer:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      options: --user root
    steps:
      - name: download RepoRT
        uses: actions/checkout@v6
        with:
          repository: michaelwitting/RepoRT
          path: RepoRT
      - name: test prediction
        run: |
          python predict.py  --model models/2-step0525.pt --repo_root_folder RepoRT \
                 --input_compounds test/test_input.tsv --input_metadata test/test_metadata.yaml --output_roi
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
